// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
    
  }

  

 static const FirebaseOptions web = FirebaseOptions(
  apiKey: "AIzaSyAyHk9aolgqf67KP9Ds7uOkOFSs787Jl2U",
  authDomain: "paceo-4409d.firebaseapp.com",
  projectId: "paceo-4409d",
  storageBucket: "paceo-4409d.firebasestorage.app",
  messagingSenderId: "238691630194",
  appId: "1:238691630194:web:931eb86754e8642d8b16eb",
  measurementId: "G-CPNVSEVB34",
);


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSK03_2xb3Memew0MCybsSJ7z5G8dE7JA',
    appId: '1:238691630194:android:d26eb193276549798b16eb',
    messagingSenderId: '238691630194',
    projectId: 'paceo-4409d',
    storageBucket: 'paceo-4409d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_s1R-jeFSHYmQUUj44n_urA6XF_QqHt8',
    appId: '1:238691630194:ios:844e705d5bfe47118b16eb',
    messagingSenderId: '238691630194',
    projectId: 'paceo-4409d',
    storageBucket: 'paceo-4409d.firebasestorage.app',
    iosBundleId: 'com.example.paceo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_s1R-jeFSHYmQUUj44n_urA6XF_QqHt8',
    appId: '1:238691630194:ios:844e705d5bfe47118b16eb',
    messagingSenderId: '238691630194',
    projectId: 'paceo-4409d',
    storageBucket: 'paceo-4409d.firebasestorage.app',
    iosBundleId: 'com.example.paceo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyHk9aolgqf67KP9Ds7uOkOFSs787Jl2U',
    appId: '1:238691630194:web:931eb86754e8642d8b16eb',
    messagingSenderId: '238691630194',
    projectId: 'paceo-4409d',
    authDomain: 'paceo-4409d.firebaseapp.com',
    storageBucket: 'paceo-4409d.firebasestorage.app',
    measurementId: 'G-CPNVSEV3B4',
  );

}